name: Pure Android APK Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile App via Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
          
      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MobileApp-APK
          path: bin/*.apk
